/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package d0421p;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import java.io.*;
import java.text.*;

/**
 *
 * @author master
 */
public class D0421P extends javax.swing.JFrame {

    /**
     * Creates new form D0421P
     */
  public double idLength = 0;
  public double idWidth = 0;
  public double idDepth = 0;
  public double odLength = 0;
  public double odWidth = 0;
  public double odDepth = 0;
  public double frontFlap = 0;
  public double lidTab = 0;
    
    public D0421P() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDC = new javax.swing.ButtonGroup();
        cflutetype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        wsz = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dsz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFilePathName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        blksz = new javax.swing.JLabel();
        dimtype = new javax.swing.JComboBox<>();
        createDxf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBlkSz = new javax.swing.JButton();
        lsz = new javax.swing.JTextField();
        r2r2upint = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtlockslot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtlocklug = new javax.swing.JTextField();
        txttoe = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtfrontflap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txttabplus = new javax.swing.JTextField();
        txtlidtab = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cBreezePaper = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        BtnBreeze = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("D/C 0421+ 4pt GL - Mailbox");

        cflutetype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "E", "B", "C", "BC", "Carton Brd" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Flute:");

        jLabel5.setText("x");

        dsz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dszFocusLost(evt);
            }
        });

        jLabel6.setText("x");

        txtFilePathName.setText("aaNewDrawing.dxf");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("File Name:");

        blksz.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blksz.setText("1up Blank Size:");

        dimtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID: Internal Dimensions", "BB: Bend to Bend", "OD: Outside Dimensions" }));

        createDxf.setText("Create DXF Drawing");
        createDxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDxfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Dim Type:");

        btnBlkSz.setText("Calc Blank Size");
        btnBlkSz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlkSzActionPerformed(evt);
            }
        });

        lsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lszActionPerformed(evt);
            }
        });

        r2r2upint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        r2r2upint.setText("Interlock:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Pack Size:");

        txtlockslot.setText("20");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Lock SLot:");

        txtlocklug.setText("3.5");

        txttoe.setText("45");
        txttoe.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttoeFocusLost(evt);
            }
        });
        txttoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttoeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Lock Lug:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("TOE:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Front Flap:");

        txttabplus.setText("1.5");

        txtlidtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlidtabActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Lid Tab+:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Lid Tab D:");

        cBreezePaper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black (1000mm Reel)", "White (1180mm Reel)", "Blue (1000mm Reel)" }));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("Breeze Paper");

        BtnBreeze.setText("Breeze Paper");
        BtnBreeze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBreezeActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Band Print");

        buttonGroupDC.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Elite");

        buttonGroupDC.add(jRadioButton2);
        jRadioButton2.setText("Iberica");

        buttonGroupDC.add(jRadioButton3);
        jRadioButton3.setText("Topra (Rotary D/C)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(blksz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttoe, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtlockslot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtlidtab, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfrontflap, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtlocklug, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txttabplus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cBreezePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cflutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnBreeze, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox2)
                            .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 93, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(wsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(dsz, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttoe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txtlockslot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtlocklug, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlidtab, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtfrontflap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txttabplus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBreezePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFilePathName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cflutetype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BtnBreeze, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blksz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r2r2upint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBlkSz, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createDxf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton3)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createDxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDxfActionPerformed
   getSizes();
    
    String outputDxfData = "";   
    
    // **** WARNINGS ****
    makeUpCheck oChk = new makeUpCheck();
    oChk.w = Double.parseDouble(wsz.getText());
    oChk.d = Double.parseDouble(dsz.getText());
    oChk.lidTab = this.lidTab;
    oChk.d0421pMakeUpCheck();
    // ************************************
    
    draw0421pcls oDxf = new draw0421pcls();
    oDxf.allowanceSetup();
    
    oDxf.xabs = 0;
    oDxf.yabs = 0;
    oDxf.length = this.idLength;
    oDxf.width = this.idWidth;
    oDxf.depth = this.idDepth;
    oDxf.slot = Double.parseDouble(txtlockslot.getText());
    oDxf.toeflap = Double.parseDouble(txttoe.getText());
    oDxf.lug = Double.parseDouble(txtlocklug.getText());
    
    oDxf.lidtabD = Double.parseDouble(txtlidtab.getText());
    oDxf.frontFlap = Double.parseDouble(txtfrontflap.getText());
    oDxf.lidTabAdd = Double.parseDouble(txttabplus.getText());
    
    oDxf.unit = "M";
    oDxf.style = "";
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.cutlay = "CUT";
    oDxf.crelay = "CREASE";
    oDxf.dxf = ""; // Output File's contents
    oDxf.dxfxmax = String.valueOf(0);
    oDxf.dxfymax = String.valueOf(0);
    
    oDxf.Xaxis = 1; // Direction of X axis +1 or -1
    oDxf.Yaxis = 1; // Direction of Y axis +1 or -1
    
    outputDxfData = oDxf.Draw0421p();
    
    String outputDir = ""; // "../temp/";
    File f = new File(outputDir + txtFilePathName.getText());
    if(f.exists() && !f.isDirectory()) { 
      f.delete();
    }
    String outputDxfFile = outputDir + txtFilePathName.getText(); // "testfilel.dxf"; // "/var/www/temp/testfilel.dxf";
    
    BufferedWriter writer = null; // Note outside try block
    try {
      //create a file
      File newDxfFile = new File(outputDxfFile);
      
      writer = new BufferedWriter(new FileWriter(newDxfFile));
      writer.write(outputDxfData);
      writer.flush();
    } catch (Exception e) {
      e.printStackTrace();
    } finally {
      try {
        // Close the writer regardless of what happens...
        writer.close();
      } catch (Exception e) {
      }
    }
    JOptionPane.showMessageDialog(null, "Saved: " + outputDxfFile); 

    }//GEN-LAST:event_createDxfActionPerformed

    private void btnBlkSzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlkSzActionPerformed
      // **** WARNINGS ****
      makeUpCheck oChk = new makeUpCheck();
      oChk.w = Double.parseDouble(wsz.getText());
      oChk.d = Double.parseDouble(dsz.getText());
      oChk.lidTab = this.lidTab;
      oChk.d0421pMakeUpCheck();
      // ************************************
      
	String msg = "";
    
    getSizes();
    draw0421pcls oDxf = new draw0421pcls();
    
    oDxf.length = this.idLength;
    oDxf.width = this.idWidth;
    oDxf.depth = this.idDepth;
    oDxf.toeflap = Double.parseDouble(txttoe.getText());
    
    oDxf.lidtabD = Double.parseDouble(txtlidtab.getText());
    oDxf.frontFlap = Double.parseDouble(txtfrontflap.getText());
    
    oDxf.unit = "M";
    oDxf.flute = (String) cflutetype.getSelectedItem();    
    oDxf.allowanceSetup();
    
    BoardSz oMc = new BoardSz();
    oMc.blkS1 = oDxf.blks1;
    oMc.blkN2 = oDxf.blkn2;
    oMc.blkInsetN2 = oDxf.blkn2IntLk; //375;
    oMc.blkInsetS1 = oDxf.blks1; //350;
    oMc.diecutter = "Elite";
    oMc.asymmetrical = false;
    msg = oMc.CalcR2R();
    
    blksz.setText("1up Blank Size: " + oDxf.blks1 +  " x " + oDxf.blkn2); 
    // r2r2upint.setText("INTERLOCK: " +  + oDxf.noUpS1 + "up " + oDxf.interlockblks1 + " x " + oDxf.interlockblkn2 + " " + oDxf.noUpN2 + "up");
    r2r2upint.setText(msg);

    }//GEN-LAST:event_btnBlkSzActionPerformed

    private void lszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lszActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lszActionPerformed

    private void txttoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttoeActionPerformed

    private void txtlidtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlidtabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlidtabActionPerformed

    private void dszFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dszFocusLost
    try { 
      getSizes();
      
      blksz.setText("1up Blank Size: ");
      if (lidTab > 85) {
        lidTab = (int)Math.floor(lidTab * 0.4);
        if (lidTab > 85) {lidTab = 85;}
        if (lidTab < 45) {lidTab = 45;}
      }
      if (Double.parseDouble(wsz.getText()) > 350 ) {
        txtlocklug.setText("5");
      }
      txtfrontflap.setText(String.valueOf(frontFlap));
      txtlidtab.setText(String.valueOf(lidTab));
      
      // **** WARNINGS ****
      makeUpCheck oChk = new makeUpCheck();
      oChk.w = Double.parseDouble(wsz.getText());
      oChk.d = Double.parseDouble(dsz.getText());
      oChk.lidTab = this.lidTab;
      oChk.d0421pMakeUpCheck();
      // ************************************
      
    } catch(Exception e) {
      System.err.println("ERROR: " + e.getMessage());
      e.printStackTrace();
    } finally {
      
    } // end of try 
    }//GEN-LAST:event_dszFocusLost

    private void txttoeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttoeFocusLost
        double dtoe = Double.parseDouble(txttoe.getText());
    
        if (dtoe <= 45) {
          txtlockslot.setText("20");
        }
        if (dtoe == 46) {
          txtlockslot.setText("21");
        }
        if (dtoe == 47) {
          txtlockslot.setText("22");
        }
        if (dtoe == 48) {
          txtlockslot.setText("23");
        }
        if (dtoe == 49) {
          txtlockslot.setText("24");
        }
        if (dtoe > 49) {
          txtlockslot.setText("25");
        }
        if (dtoe > 59) {
          txtlockslot.setText("30");
        }    
    }//GEN-LAST:event_txttoeFocusLost

    
    private void BtnBreezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBreezeActionPerformed
    // Take input sizes and find true ID & OD
    double l = Double.parseDouble(lsz.getText());
    double w = Double.parseDouble(wsz.getText());
    double d = Double.parseDouble(dsz.getText());
    double breezeReelWdith = 1000;
    // Get Allowances
    draw0421pcls oDxf = new draw0421pcls();
    oDxf.length = 0;
    oDxf.width = 0;
    oDxf.depth = 0;
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.allowanceSetup();
    
    getSizes();
    double ol = 25; // Paper Overlap
    double glOnBase = 25; // Insert glue section on front depth
    double btmPnlCutback = 15;
    double pD = this.idDepth + oDxf.dmain;
    double tmp = glOnBase + this.idWidth + oDxf.winner + ((pD) * 2) + ol; // Total Paper Length
    double paperW = this.idLength - 15; //8;
    double paperLbase = glOnBase + this.idWidth + oDxf.winner - btmPnlCutback; // Optimum size
    double paperLlid = tmp - paperLbase;   
    
    if((paperLbase + paperLlid) > breezeReelWdith) {
      JOptionPane.showMessageDialog(null, "If both sizes added together > 1000 then 2 passes\nmay be required to apply Breeze Paper\n" + String.format("A + B =%10.1f", (paperLbase + paperLlid)), "Breeze Paper Problem", JOptionPane.ERROR_MESSAGE);
    } // end of if
    if((paperLbase > breezeReelWdith) || (paperLlid > breezeReelWdith)) {
      JOptionPane.showMessageDialog(null, "Largest Paper size > 1000 then too big to make on Kohmann\n", "Breeze Paper ERROR", JOptionPane.ERROR_MESSAGE);  
    } // end of if 
    if((paperW > 400)) {
      JOptionPane.showMessageDialog(null, "Paper Width > 400 Possibly too big to make on Kohmann CHECK\n", "Breeze Paper ERROR", JOptionPane.ERROR_MESSAGE);  
    } // end of if 
    
    blksz.setText("BREEZE PAPER - Base :" + paperW + " x " + paperLbase + "   / Lid :" + paperW + " x " + paperLlid);

    }//GEN-LAST:event_BtnBreezeActionPerformed

    
      public void getSizes() {
    // Take input sizes and find true ID & OD
    double l = Double.parseDouble(lsz.getText());
    double w = Double.parseDouble(wsz.getText());
    double d = Double.parseDouble(dsz.getText());
    double lengthPlus = 0; // Bulge Figures
    double widthPlus = 0;
    double depthPlus = 0;
    // Get Allowances
    draw0421pcls oDxf = new draw0421pcls();
    oDxf.length = 0;
    oDxf.width = 0;
    oDxf.depth = 0;
    oDxf.flute = (String) cflutetype.getSelectedItem();
    oDxf.allowanceSetup();
    
    if (dimtype.getSelectedItem() == "ID: Internal Dimensions") {
      this.idLength = l; 
      this.idWidth = w;
      this.idDepth = d;   
    } else if (dimtype.getSelectedItem() == "OD: Outside Dimensions") {      
      if (cflutetype.getSelectedItem().toString() == "B") {   // put Bulge figres here later if necessary
      } else if(cflutetype.getSelectedItem().toString() == "C") {
      } else if(cflutetype.getSelectedItem().toString() == "BC") {  
      } else { // E flute  
      } // end if  
      this.idLength = l - oDxf.dataArray[4] - oDxf.odAlw - lengthPlus; // Assumes TOE section is Size given 
      this.idWidth = w - oDxf.dataArray[6] - oDxf.odAlw - widthPlus;  // assumes outer Width specified
      this.idDepth = d - oDxf.dataArray[0] - oDxf.odAlw - depthPlus;
      
    } else { // Bend to Bend
      this.idLength = l - oDxf.dataArray[4]; // Size - Allowance
      this.idWidth = w - oDxf.dataArray[5]; // assumes inner Width specified
      this.idDepth = d - oDxf.dataArray[0];
    } 
    // Set Front Flap & LidTab
    frontFlap = this.idDepth + oDxf.dataArray[2];
    lidTab = this.idDepth; // Max possible size - Amended in dsz_FocusLost
    // Find O/D
    this.odLength = this.idLength + oDxf.dataArray[4] + oDxf.odAlw + lengthPlus; 
    this.odWidth = this.idWidth + oDxf.dataArray[6] + oDxf.odAlw + widthPlus;
    this.odDepth = this.idDepth + oDxf.dataArray[0] + oDxf.odAlw + depthPlus;
    
    parcelSizes oBjt = new parcelSizes();
    oBjt.odLength = this.odLength;
    oBjt.odWidth = this.odWidth;
    oBjt.odDepth = this.odDepth;
    oBjt.checkSizes();
    
  } // getSizes

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D0421P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D0421P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D0421P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D0421P.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D0421P().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBreeze;
    private javax.swing.JLabel blksz;
    private javax.swing.JButton btnBlkSz;
    private javax.swing.ButtonGroup buttonGroupDC;
    private javax.swing.JComboBox<String> cBreezePaper;
    private javax.swing.JComboBox<String> cflutetype;
    private javax.swing.JButton createDxf;
    private javax.swing.JComboBox<String> dimtype;
    private javax.swing.JTextField dsz;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField lsz;
    private javax.swing.JLabel r2r2upint;
    private javax.swing.JTextField txtFilePathName;
    private javax.swing.JTextField txtfrontflap;
    private javax.swing.JTextField txtlidtab;
    private javax.swing.JTextField txtlocklug;
    private javax.swing.JTextField txtlockslot;
    private javax.swing.JTextField txttabplus;
    private javax.swing.JTextField txttoe;
    private javax.swing.JTextField wsz;
    // End of variables declaration//GEN-END:variables
}
